name: seoul server cd
on:
  push:
    branches:
      - "main"
     
jobs:
  server-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/seoul00-backend
            sudo git pull
            sudo docker-compose down
            sudo docker-compose up --build -d